// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcN8nDLCayX8Db343xPyyvk97-e3z4zG0',
    appId: '1:428961579625:web:a741a55ccaf4767976d8f8',
    messagingSenderId: '428961579625',
    projectId: 'innercircle2025',
    authDomain: 'innercircle2025.firebaseapp.com',
    storageBucket: 'innercircle2025.firebasestorage.app',
    measurementId: 'G-E3KW4VFK8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpbCDHtWyITDnn7viEMhKsBu3U9mpoEtk',
    appId: '1:428961579625:android:3badd6558469841276d8f8',
    messagingSenderId: '428961579625',
    projectId: 'innercircle2025',
    storageBucket: 'innercircle2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7RFCbMIWMwEvtKXnlqt74UV-FLolnm9o',
    appId: '1:428961579625:ios:2572dc4715226c8576d8f8',
    messagingSenderId: '428961579625',
    projectId: 'innercircle2025',
    storageBucket: 'innercircle2025.firebasestorage.app',
    androidClientId: '428961579625-rmcs3aa05g52ig17lvmhium54irh3no0.apps.googleusercontent.com',
    iosClientId: '428961579625-107shrd8qs5hiijh9u9fprp0su87gj8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.innerCircle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7RFCbMIWMwEvtKXnlqt74UV-FLolnm9o',
    appId: '1:428961579625:ios:2572dc4715226c8576d8f8',
    messagingSenderId: '428961579625',
    projectId: 'innercircle2025',
    storageBucket: 'innercircle2025.firebasestorage.app',
    androidClientId: '428961579625-rmcs3aa05g52ig17lvmhium54irh3no0.apps.googleusercontent.com',
    iosClientId: '428961579625-107shrd8qs5hiijh9u9fprp0su87gj8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.innerCircle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcN8nDLCayX8Db343xPyyvk97-e3z4zG0',
    appId: '1:428961579625:web:8d3bcccc1b20c8d976d8f8',
    messagingSenderId: '428961579625',
    projectId: 'innercircle2025',
    authDomain: 'innercircle2025.firebaseapp.com',
    storageBucket: 'innercircle2025.firebasestorage.app',
    measurementId: 'G-NR9668F090',
  );
}
